from pathlib import Path
import pandas as pd

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig


mcfg = ModuleConfig(
    module_name='reference_mapping',
    config=config,
    config_params=['scarches', 'threads'],
)
paramspace = mcfg.get_paramspace()


module preprocessing:
    snakefile: "../../preprocessing/rules/rules.smk"
    config: config

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

include: 'rules/scarches.smk'
include: 'rules/umap.smk'


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True


rule all:
    input:
        mcfg.get_output_files(),
        mcfg.get_output_files(rules.reference_mapping_plot_umap.output),
    default_target: True
    localrule: True