from pathlib import Path
import pandas as pd

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig


mcfg = ModuleConfig(
    module_name='reference_mapping',
    config=config,
    config_params=[
        'scarches',
        'scimilarity',
        'threads',
    ],
)
paramspace = mcfg.get_paramspace()


module preprocessing:
    snakefile: "../../preprocessing/rules/rules.smk"
    config: config

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


def get_input(wildcards, model_name='scarches'):
    file_map = dict(
        zarr=mcfg.get_input_file(**wildcards),
    )
    model_path = mcfg.get_from_parameters(wildcards, model_name, default={}).get('model')
    if model_path is not None:
        file_map['model'] = model_path
    return file_map


include: 'rules/scarches.smk'
include: 'rules/scimilarity.smk'
include: 'rules/umap.smk'


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True


rule all:
    input:
        [
            mcfg.get_output_files(rules.scarches.output, subset_dict=dict(dataset=dataset))
            for dataset in mcfg.get_datasets()
            if mcfg.get_from_parameters(dict(dataset=dataset), 'scarches', default={}).get('model') is not None
        ],
        mcfg.get_output_files(rules.reference_mapping_plot_umap.output),
    default_target: True
    localrule: True