  output_dir: data/out
  images: images
  use_gpu: false

  DATASETS:

    my_dataset: # custom task/workflow name

      # input specification: map of module name to map of input file name to input file path
      input:
        preprocessing:
          file_1: data/pbmc68k.h5ad
        integration: preprocessing
        metrics: integration
      
      # module configuration
      preprocessing:
        highly_variable_genes:
          n_top_genes: 2000
        pca:
          n_comps: 50
        assemble:
          - normalize
          - highly_variable_genes
          - pca
      
      # module configuration
      integration:
        raw_counts: layers/counts
        norm_counts: layers/normcounts
        batch: batch
        methods:
          unintegrated:
          bbknn:
          combat:
          harmony_pytorch:
          harmonypy:
          scanorama:
            batch_size: 100
          scvi:
            max_epochs: 10
            early_stopping: true
          drvi:
            max_epochs: 10
            early_stopping: true
            devices: 1
            accelerator: cpu
          sysvi:
            max_epochs: 10
            early_stopping: true
            system_key: phase

      # module configuration
      metrics:
        unintegrated: layers/normcounts
        batch: batch
        label: bulk_labels
        methods:
          - asw_batch
          - graph_connectivity
          - ilisi
          - pcr_comparison
          - ari
          - asw_label
          - cell_cycle
          - clisi
          - isolated_label_asw
          - isolated_label_f1
          - nmi
          - morans_i_random
          - ari_leiden_y
          - ari_kmeans_y
          - nmi_leiden_y
          - nmi_kmeans_y
          - asw_label_y
          - asw_batch_y
          - ilisi_y
          - clisi_y
          - isolated_label_asw_y
          - kbet_y
          - kbet_pg
          - graph_connectivity_y
          - pcr_random
          - pcr
          - pcr_genes